Make it easier for new developers to get started
rht-labs/infographic pull request #16
Opened 2018-01-10 21:36 UTC by rdebeasi

This PR fixes some quirks with documentation and code, making it a bit easier to get started working on the project.

- Include readme updates from @InfoSec812 (see #4), with accurate "getting started" steps and documentation on environment variables.
- The local dev front end can now talk to the local dev back end. (Before, the port number was wrong and requests to the back end didn't work).
- Remove extraneous "utils" code responsible for the above bug.
- Rename `window.internal` to `window.rhtLabsInternal` to clarify that it's a global variable from our application, not a property provided by the browser (like the nonstandard but widely supported `window.external`).
- `if (window.internal && window.internal == true){` doesn't do what the developer probably thought it did. Clarified to just `if (window.rhtLabsInternal){`
- When starting the application, output the full URL. This results in a link that can be clicked in many terminals.

CC @mwalker5000

2018-01-10 22:05 UTC, sherl0cks commented
be advised.

IMHO - this looks fine Ryan, but I'd like to know @oybed is cool with these types of changes, as he has been much closer to this repo than I have.

2018-01-10 22:11 UTC, oybed commented
Yeah, I’d like to review it (and test it). I’ll put it in my list for
tomorrow.


On Jan 10, 2018, at 5:05 PM, Justin Holmes <notifications@github.com> wrote:

be advised.

IMHO - this looks fine Ryan, but I'd like to know @oybed
<https://github.com/oybed> is cool with these types of changes, as he has
been much closer to this repo than I have.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rht-labs/infographic/pull/16#issuecomment-356752542>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AHMzWVAfB9yLvUAWbOgFL9fevBOOns0jks5tJTQXgaJpZM4RZ-yF>
.

2018-01-10 22:14 UTC, oybed commented
But, yes, in general not a “big fan” of clean-up changes to this repo (for multiple reasons - we can discuss offline).

2018-01-10 22:17 UTC, rdebeasi commented
Totally understandable. For what it's worth, the focus here was on improving documentation and fixing a bug that prevented the application from working properly on local. The only pure "cleanup" work was renaming `internal` to `rhtInternal` and simplifying those `if` statements.

2018-01-16 19:03 UTC, oybed requested changes
@rdebeasi some comments inline ... will ping you a few things offline as well

2018-01-16 19:03 UTC, oybed commented on README.md
> +- `/internal.html`: The "internal" version of infographic. Clicking the "build" button kicks off an Ansible job.
I know this is something that can be figured out by reading the code, but exposing it in the docs makes this "hidden by obscurity" approach a bit "less hidden".

2018-01-16 19:03 UTC, oybed commented on README.md
> +- `/stack`: The node.js API that the front end hits when the user clicks the "build" button. This API passes the request on to Ansible.
Same comment as above -- if kept, I'd like to change `... request on to Ansible.` to `... request on to Ansible Tower (per configuration params below)`.

2018-01-16 19:03 UTC, oybed commented on index.js
> +		console.log('Listening on http://localhost:' + httpPort);
I'd like to continue to call out the `UNSECURE` aspect of this message

2018-01-16 19:03 UTC, oybed commented on package-lock.json
> +{
I know this is "best practices", but is it needed? It adds extra maintenance.

2018-01-16 19:03 UTC, oybed commented on website/js/app.js
> +                    var url = '/stack'
With this clean-up, it seems a waste to keep the variable - eliminate?

2018-01-16 19:03 UTC, oybed commented on README.md
> +This will start up a local http server to host the fron using the `website` directory as the root context of the front end application. This local devleopment server will also host the API. In OpenSh
I know the templates are mentioned here, but would like maybe give them their own dedicated section. That's the primary way to run this.

2018-01-16 20:41 UTC, oybed approved these changes

2018-01-16 20:41 UTC, merged